name: Python Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Create and activate the virtual environment
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flask flask-cors
        working-directory: ./test_cicd

      # Run tests or start the Flask app
      - name: Run tests
        run: |
          source venv/bin/activate
          # Here you would run unit tests or start your Flask app
          # python app.py  (if running app)
        working-directory: ./test_cicd
